# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName-be: 'selenium-demo-mywebapi:$(build.buildId)'
  imageName-fe: 'selenium-demo-webfrontend:$(build.buildId)'
  dockerId: 'mknowlescr'

steps:
- script: docker build -f ./src/mywebapi/Dockerfile -t $(imageName-be) ./src/mywebapi
  displayName: 'docker be build'
- script: docker build -f ./src/webfrontend/Dockerfile -t $(imageName-fe) ./src/webfrontend
  displayName: 'docker fe build'
- script: |
    docker tag $(imageName-be) $(dockerId).azurecr.io/$(imageName-be)
    docker tag $(imageName-fe) $(dockerId).azurecr.io/$(imageName-fe)
    docker login $(dockerid).azurecr.io -u $(dockerId) -p $(cr-pswd)
    docker push $(dockerId).azurecr.io/$(imageName-be)
    docker push $(dockerId).azurecr.io/$(imageName-fe)
  displayName: 'container registry push'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './src/mywebapi/charts/mywebapi' 
    artifactName: 'be-charts' 
  displayName: 'publish be charts'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './src/webfrontend/charts/webfrontend' 
    artifactName: 'fe-charts' 
  displayName: 'publish fe charts'



